import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const digital7 = localFont({
  src: [
    {
      path: "../public/digital-7-font-family/digital-7-mono.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/digital-7-font-family/digital-7-mono-italic.ttf",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-digital7",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${digital7.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
